### ISSUE TITLE
Issue when loading the model

### ISSUE THREAD

**Issue by floschne** [ufal/crac2023-corpipe#3]
Hi, and thanks for this amazing work!

I just tried to test your model on some files of mine but, I got an error when loading the model:

This is the command I use to run the code:

`CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=1  python corpipe23.py --load model/corpipe23-corefud1.1-231206/model.h5 --exp . --epoch 0 --test  ./m_1759_easy.conllu2_tagged`

The model was downloaded as described from `https://hdl.handle.net/11234/1-5369` on June 18th.
However, it seems that the weights in the H5 file do not match the architecture.

This is the log with the error message at the bottom:

```python
2024-06-19 07:16:18.236935: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-19 07:16:18.236988: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-19 07:16:18.238655: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
/ltstorage/home/7schneid/miniforge3/envs/coref/lib/python3.10/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning:

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP).

For more information see: https://github.com/tensorflow/addons/issues/2807

  warnings.warn(
WARNING:tensorflow:From /ltstorage/home/7schneid/miniforge3/envs/coref/lib/python3.10/site-packages/tensorflow/python/util/deprecation.py:588: calling function (from tensorflow.python.eager.polymorphic_function.polymorphic_function) with experimental_relax_shapes is deprecated and will be removed in a future version.
Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/ltstorage/home/7schneid/miniforge3/envs/coref/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
/ltstorage/home/7schneid/miniforge3/envs/coref/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/ltstorage/home/7schneid/miniforge3/envs/coref/lib/python3.10/site-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(
Traceback (most recent call last):
  File "/ltstorage/home/7schneid/projects/hcds/coref/crac2023-corpipe/corpipe23.py", line 715, in <module>
    main([] if "__file__" not in globals() else None)
  File "/ltstorage/home/7schneid/projects/hcds/coref/crac2023-corpipe/corpipe23.py", line 687, in main
    model = (ModelEnsemble if len(args.load) > 1 else Model)(tokenizer, tags, args)
  File "/ltstorage/home/7schneid/projects/hcds/coref/crac2023-corpipe/corpipe23.py", line 320, in __init__
    self.load_weights(args.load[0])
  File "/ltstorage/home/7schneid/miniforge3/envs/coref/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/ltstorage/home/7schneid/miniforge3/envs/coref/lib/python3.10/site-packages/keras/src/saving/legacy/hdf5_format.py", line 819, in load_weights_from_hdf5_group
    raise ValueError(
ValueError: Layer count mismatch when loading weights from file. Model expected 6 layers, found 7 saved layers.
```

Do you have any idea how to solve this issue?

**Comment by foxik** [comment]
Could you send `pip list` from your environment? Currently I cannot reproduce your error.

**Comment by floschne** [comment]
Thanks for your quick reply! 

This is the output of `pip freeze`:

```python
absl-py==2.1.0
aiohttp==3.9.5
aiosignal==1.3.1
alembic==1.13.1
anyio==4.3.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
astunparse==1.6.3
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
Babel==2.14.0
banal==1.0.6
beautifulsoup4==4.12.3
bleach==6.1.0
cachetools==5.3.2
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
colorama==0.4.6
comm==0.2.2
dataset==1.6.2
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.8
exceptiongroup==1.2.1
executing==2.0.1
fastjsonschema==2.19.1
fasttext==0.9.2
filelock==3.13.4
fire==0.5.0
flake8==6.0.0
flatbuffers==24.3.25
fqdn==1.5.1
frozenlist==1.4.1
fsspec==2024.3.1
gast==0.5.4
gdown==5.2.0
google-auth==2.30.0
google-auth-oauthlib==1.2.0
google-pasta==0.2.0
grpcio==1.64.1
h11==0.14.0
h5py==3.11.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.23.4
idna==3.7
iniconfig==2.0.0
ipykernel==6.29.4
ipython==8.24.0
ipywidgets==8.1.2
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.3
json5==0.9.25
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyter_server==2.14.0
jupyter_server_terminals==0.5.3
jupyterlab==4.1.8
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.1
jupyterlab_widgets==3.0.10
keras==2.15.0
libclang==18.1.1
Mako==1.3.3
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mccabe==0.7.0
mdurl==0.1.2
mistune==3.0.2
ml-dtypes==0.3.2
multidict==6.0.5
multiprocess==0.70.16
namex==0.0.8
nbclient==0.10.0
nbconvert==7.16.3
nbformat==5.10.4
nest-asyncio==1.6.0
notebook==7.1.3
notebook_shim==0.2.4
numpy==1.26.4
nvidia-cublas-cu12==12.3.4.1
nvidia-cuda-cupti-cu12==12.3.101
nvidia-cuda-nvcc-cu12==12.3.107
nvidia-cuda-nvrtc-cu12==12.3.107
nvidia-cuda-runtime-cu12==12.3.101
nvidia-cudnn-cu12==8.9.7.29
nvidia-cufft-cu12==11.0.12.1
nvidia-curand-cu12==10.3.4.107
nvidia-cusolver-cu12==11.5.4.101
nvidia-cusparse-cu12==12.2.0.103
nvidia-ml-py==12.535.133
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.3.101
nvitop==1.3.2
oauthlib==3.2.2
opt-einsum==3.3.0
optree==0.11.0
overrides==7.7.0
packaging==24.1
pandas==2.2.2
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
platformdirs==4.2.1
pluggy==1.5.0
prometheus_client==0.20.0
prompt-toolkit==3.0.43
protobuf==4.25.3
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow-hotfix==0.6
pyasn1==0.6.0
pyasn1_modules==0.4.0
pybind11==2.12.0
pycodestyle==2.10.0
pycparser==2.22
pyflakes==3.0.1
Pygments==2.18.0
PySocks==1.7.1
pytest==8.2.2
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pytz==2024.1
PyYAML==6.0.1
pyzmq==26.0.2
qtconsole==5.5.1
QtPy==2.4.1
referencing==0.35.0
regex==2024.4.16
requests==2.32.3
requests-oauthlib==2.0.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.1
rpds-py==0.18.0
rsa==4.9
safetensors==0.4.3
scipy==1.13.1
Send2Trash==1.8.3
sentencepiece==0.2.0
six==1.16.0
sniffio==1.3.1
soupsieve==2.5
SQLAlchemy==1.4.52
stack-data==0.6.3
tensorboard==2.15.2
tensorboard-data-server==0.7.2
tensorflow==2.15.1
tensorflow-addons==0.23.0
tensorflow-estimator==2.15.0
tensorflow-io-gcs-filesystem==0.37.0
termcolor==2.4.0
terminado==0.18.1
tf_keras==2.16.0
tinycss2==1.3.0
tokenizers==0.19.1
tomli==2.0.1
tornado==6.4
tqdm==4.66.2
traitlets==5.14.3
transformers==4.41.2
typeguard==2.13.3
types-python-dateutil==2.9.0.20240316
typing_extensions==4.12.2
tzdata==2024.1
udapi @ git+https://github.com/udapi/udapi-python@d98beee9878adef71661a4d59abcba509db49053
ufal.chu_liu_edmonds==1.0.3
ufal.udpipe==1.3.1.1
uri-template==1.3.0
urllib3==2.2.2
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.8.0
Werkzeug==3.0.3
widgetsnbextension==4.0.10
wrapt==1.14.1
xxhash==3.4.1
yarl==1.9.4
```

**Comment by foxik** [comment]
I think the problem is the too new version of TensorFlow -- the https://github.com/ufal/crac2023-corpipe/blob/master/requirements.txt wants TF 2.12.*. (Unfortunately, TensorFlow is changing nontrivially even between minor versions.) Could you please try creating a new virtual environment according to `requirements.txt` to verify it?

Of course, it would be unfortunate if CorPipe23 did not work with newer TensorFlow; however, I am currently working on a new version (the one for CRAC 24) and it will be implemented in PyTorch.

**Comment by floschne** [comment]
Thanks that solved the issue!

**Comment by floschne** [comment]
@foxik , does it work for you with GPU support when `pip install -r requirements.txt`? For me, it doesn't and unfortunately,  when installing a newer tensorflow version (with GPU support), the issue mentioned above happens again. Can you please provide your pip env :-) ?

**Comment by foxik** [comment]
Yes, GPU support works for me when I use the requirements.txt (my venv is created exactly by running `pip install -r requirements.txt`). You of course need CUDA 11.* installed, with correct paths in the usual environmental variables -- for example, my config is the following:
```
export PATH="/opt/cuda/11.8/bin:$PATH"
export XLA_FLAGS=--xla_gpu_cuda_data_dir=/opt/cuda/11.8
export LD_LIBRARY_PATH="/opt/cuda/11.8/lib64:/opt/cuda/11.8/cudnn/8.9.2/lib:/opt/cuda/11.8/nccl/2.15.5/lib:/opt/cuda/11.8/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
```

**Comment by floschne** [comment]
Okay, I'm afraid, I only have a system with CUDA 12. Didn't know that Tensorflow 2.12 only supports CUDA 11

**Comment by foxik** [comment]
The CUDA versions of the official TensorFlow builds are here: https://www.tensorflow.org/install/source#gpu . If you have CUDA 12 GPUs only, then you either need TensorFlow 2.15+, or you would need to build TF 2.12 manually with CUDA 12 (that might or might not work, and would require some effort).

For the time being, I do not want to invest time in upgrading the TF support in CorPipe (given that it is a research prototype), but if it is still relevant, you can ask in two weeks, when I will have more time.

**Comment by floschne** [comment]
Thanks for the offer! I'm currently trying to build TF2.12 from source .. let's see
